### ISSUE TITLE
strange crash when calling owr_bridge_start_in_thread()

### ISSUE THREAD

**Issue by portwatcher** [EricssonResearch/openwebrtc-ios-sdk#20]
Firstly I built OpenWebRTC.framework 0.1 with Cerbero myself, it turned out that some lib in it does not support arm64, I can't submit an app that doesn't support arm64 to App Store.

Then I found this repo, however, I failed `pod update` with some error like `no such file chmod_internal /path/to/pods/OpenWebRTC.framework/Commands`.

But I noticed I got a OpenWebRTC.framework 0.3.1 in my cocoapods' cache. So I just replace my 0.1 framework with 0.3.1 framework, and it worked, support arm64, no crash, capable of video chat with my peer.

However my app got rejected by Apple because it crashes at launch.

I find that, when I install the app into my iPhone through XCode, everything is OK. However, when I archive it into ipa and send it to somebody, it crashes when calling `owr_bridge_start_in_thread`, because when I comment out this line of code, the crash disappears.

I call `owr_bridge_start_in_thread()` according to the bowser project. I'm wondering if this is a bug or wrong configuration with XCode or I'm using this lib wrongly.

Recently I'm really unlucky...

**Comment by portwatcher** [comment]
I noticed that there's a method in OpenWebRTC.h of this repo called `initialize` and inside this method we called `owr_init()` and `owr_run_in_background()`. I used this two methods and nothing happened, the `getUserMedia` JS API didn't work. I also tried `[OpenWebRTC initialize]` and still bad luck.

**Comment by superdump** [comment]
There is no support for the bridge in the SDK so you can't use that `[OpenWebRTC initialize]` stuff. You need to use the OpenWebRTC pod only, not the SDK pod. Also, it was a known issue in 0.3.0 that 64-bit crashed. However, I think the 0.3.1 pod fixed that, at least it should be fixed in master.

You should be able to use the OpenWebRTC pod and then import the C headers like this:
`#import <OpenWebRTC/owr/owr.h>`

owr_bridge_start_in_thread() should work. If it doesn't, we need to investigate why it's crashing.

What is your app by the way? We're very interested to hear what people are doing with OpenWebRTC. :smile:

**Comment by superdump** [comment]
Any additional information you can obtain about the crash is very welcome.

**Comment by portwatcher** [comment]
OK, I'll try that.

---
My app's english name is [CloudBox](http://cloudbox.tinydust.cn), it's a web apps container that makes the website more like an app. You can just take it as a new generation super power web browser.

We've already supported some [PhoneGap APIs](http://docs.tinydust.cn) through `JavaScriptCore`, so I just think it would be better if we support WebRTC.

Currently it's only available on Chinese App Store. You can try the Android version if you like.
By the way, it beats Chrome on Chinese App Store some time.
![img_1454](https://cloud.githubusercontent.com/assets/2919533/7490679/10c96a26-f415-11e4-944a-f69cb8d7b8c8.PNG)

---
I can post the crash log that Apple sent me.

[crash log 1](http://a560.phobos.apple.com/us/r30/Purple7/v4/03/aa/b8/03aab822-bea7-acd2-9a54-990c6bd5036d/temp..plaqscup.crash?downloadKey3=1431098157_4ee4c5a58716588c2a5399657fd77c23)
[crash log 2](http://a303.phobos.apple.com/us/r30/Purple1/v4/14/ab/ae/14abae8b-2e74-694a-fa48-4ee9676b4823/temp..ryxjffsy.crash?downloadKey3=1431098157_5a77ef126f2554f192bee7baa121d777)
[crash log 3](http://a1787.phobos.apple.com/us/r30/Purple1/v4/69/e0/4d/69e04dc2-1afa-7207-abe2-72677b22f6fe/temp..vqgootna.crash?downloadKey3=1431098157_5c6866e436abece444a94a06a3c2a0b9)

**Comment by portwatcher** [comment]
I can't install `OpenWebRTC` by CocoaPods, it throws error after successfully copying `OpenWebRTC.framework`:
```
Errno::ENOENT - No such file or directory @ chmod_internal - /path/to/Pods/OpenWebRTC/OpenWebRTC.framework/Commands
```

And it still crashes when calling `owr_bridge_start_in_thread()` in the app installed with ipa, but goes smooth in the app installed by XCode.

**Comment by portwatcher** [comment]
How is it going? Does my crash logs help you figure it out?
I really want to contribute but I'm not good at C++.

**Comment by superdump** [comment]
I'll have a look at this when I return to work later next week unless @Rugvip beats me to it.
